// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9VfrMFc0kPVmcDEdiQ-fuWg6mYqW8fEY',
    appId: '1:909377253643:web:1d296b59b72dff7001320e',
    messagingSenderId: '909377253643',
    projectId: 'anewprojectnotes',
    authDomain: 'anewprojectnotes.firebaseapp.com',
    storageBucket: 'anewprojectnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_kZm78dHchsYL-TKgyA5MRk7uXhJ4_oI',
    appId: '1:909377253643:android:9cca12815b1689d401320e',
    messagingSenderId: '909377253643',
    projectId: 'anewprojectnotes',
    storageBucket: 'anewprojectnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi9VssGTeGy-mQ_AIzmm3b9A4OYPsGoIc',
    appId: '1:909377253643:ios:92c3d0dc58d7fb7501320e',
    messagingSenderId: '909377253643',
    projectId: 'anewprojectnotes',
    storageBucket: 'anewprojectnotes.appspot.com',
    iosClientId: '909377253643-51ml41q9a0ad37nssrs7httrnbds1pqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi9VssGTeGy-mQ_AIzmm3b9A4OYPsGoIc',
    appId: '1:909377253643:ios:222c47cd3b2eef1701320e',
    messagingSenderId: '909377253643',
    projectId: 'anewprojectnotes',
    storageBucket: 'anewprojectnotes.appspot.com',
    iosClientId: '909377253643-60u5tc0fvmsjota81fe3e5bv4vtpibju.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp.RunnerTests',
  );
}
